config/routes.rb
Rails.application.routes.draw do

  resources :problems do
    resources :proposals do
      resources :materials
    end
  end
  resources :proposals, only:[:index, :show, :edit, :update, :destroy]
  resources :materials, only:[:index, :show, :edit, :update, :destroy]
  resources :categories
  resources :comments
  resources :proposal_comments
  #resources :votes, only:[:create]


  post '/problems/:id', to: "problems#create_vote", as: "create_vote"
  #post '/problems/:id', to: "votes#create"

  root to: 'pages#home'
  #devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'users/:id', to: 'users#show', as: "user"
end

app/models/problem.rb
class Problem < ApplicationRecord
  validate :is_title_case
  before_validation :make_title_case
  validates :title, uniqueness: true
  validates :title, :content, presence: true

  has_many :problem_categories, dependent: :destroy
  has_many :categories, through: :problem_categories, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :users, through: :comments

  belongs_to :user
  has_many :proposals, dependent: :destroy
  #has_many :votes, through: :proposals

#default_scope { order(created_at: :desc) }

  def categories_attributes=(categories_attributes)
    categories_attributes.values.each do |cat_attr|
      if cat_attr[:name].present?
        category = Category.find_or_create_by(cat_attr)
        if !self.categories.include?(category)
          self.problem_categories.build(category: category)
        end
      end
    end
  end

  def fields_blank?
    self.content.empty? || self.user.empty?
  end


  def self.by_user(user_id)
    where(user: user_id)
  end

  def self.by_category(category)
    where(category: category)
  end

  def self.from_today
    where("created_at >=?", Time.zone.today.beginning_of_day)
  end

  def self.yesterday

    @from = (Time.zone.now - 1.day).beginning_of_day.utc
    @to   = (Time.zone.now).beginning_of_day.utc
    #Entry.where(:created_at => @from..@to)
    where(:created_at => @from..@to)
  end

  def self.last_week
    @from = (Time.zone.now - 7.day).beginning_of_day.utc
    @to   = (Time.zone.now).beginning_of_day.utc
    #Entry.where(:created_at => @from..@to)
    where(:created_at => @from..@to)
  end

  def self.older
    where("created_at <?", Time.zone.now - 8.day)
  end

  private

  def is_title_case
    if title.split.any?{|w|w[0].upcase != w[0]}
      errors.add(:title, "Title must be in title case")
    end
  end

  def make_title_case
    self.title = self.title.titlecase
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :set_problem, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  def index

    @users = User.all
    @categories = Category.all

    @problems = Problem.all


    if !params[:user].blank?
    @problems = Problem.by_user(params[:user])
    elsif !params[:date].blank?
      if params[:date] == "Today"
        @problems = Problem.from_today
      elsif params[:date] == "Yesterday"
        @problems = Problem.yesterday
      elsif params[:date] == "last_week"
        @problems = Problem.last_week
      else
        @problems = Problem.older
      end
    elsif !params[:category].blank?

    else
      @problems = Problem.all
    end
  end

  def show
    set_problem
    @votes = Vote.all
  end

  def new
    @problem = Problem.new
  end

  def edit
  end


  def create
    @problem = Problem.new(problem_params)
    @problem.user = current_user

      if @problem.save
        @problem.user = current_user
        redirect_to @problem, notice: 'Problem was successfully created.'
      else
        render :new
      end
  end


  def update
      if @problem.update(problem_params)
        redirect_to @problem, notice: 'Problem was successfully updated.'
      else
        render :edit
      end
  end


  def destroy
    @problem.destroy
      redirect_to problems_url, notice: 'Problem was successfully destroyed.'
  end

  def create_vote
  @problem = Problem.find_by(id:params[:id])
  @vote = Vote.new(vote_params)
  @vote.user = current_user

    if @vote.save
      @votes = Vote.all
      render "show"
    else
      render "show"
    end
  end

  private
    def set_problem
      @problem = Problem.find(params[:id])
    end

    def problem_params
      params.require(:problem).permit(:title, :content, :status, :declare_winner, category_ids:[], categories_attributes:[:name])
    end

    def vote_params
      params.require(:vote).permit(:proposal_id)
    end
end

app/helpers/problems_helper.rb
module ProblemsHelper
  def created(problem)
    problem.created_at.strftime("%m-%d-%y %H:%M")
  end

  def vote_count(proposal)
    proposal.votes.count
  end

def total_votes
   @sum = 0
   @problem.proposals.each do |proposal|
      @sum += proposal.votes.count
   end
  @sum
end

 def vote_results(proposal)
   (proposal.votes.count.to_f / total_votes) * 100
 end

 def max_vote
   @counter = 0
   @problem.proposals.each do |proposal|
     if proposal.votes.count > @counter
       @counter = proposal.votes.count
     end
    end
    @counter
  end

  def winner
    @numWinners = 0
    @winner = nil
    if @problem != nil
      @problem.proposals.each do |proposal|
        if proposal.votes.count == max_vote
          @numWinners +=1
          @winner = proposal
        end
      end
      if @numWinners == 1
        @winner
      end
    end
  end

end

app/views/problems/_form.html.erb
<%= form_with(model: problem, local: true) do |form| %>
<% if @problem.errors.any? %>
<h5 style="color: red;"><%= @problem.errors.full_messages.to_sentence %></h5>
<% end %>

  

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <br>
  Select a Category<br>
  <%= form.collection_check_boxes :category_ids, Category.all, :id, :name %>
  <br>
      Or Create New Category<br>
      <%= form.fields_for :categories, @problem.categories.build do |c| %>
        <%= c.text_field :name %>
      <% end %>


      <% if @problem.user == current_user%>
      <p>Enable Voting <%= form.check_box :status, options = {:class => "problem_active"} %></p>
      <p>Declare winner? <%= form.check_box :declare_winner, options = {:class => "problem_declare_winner"} %></p>
      <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/problems/_vote_form.html.erb
<%= form_for :vote do |form| %>
  <ul>
    <% @problem.proposals.each do |proposal|%>
      <li><%= form.radio_button :proposal_id, proposal.id%> <%= proposal.title %></li>
    <% end %>
  </ul>
    <%= form.submit "Vote" %>
<% end %>

app/views/problems/edit.html.erb
<h1>Editing Problem</h1>

<%= render 'form', problem: @problem %>

<%= link_to 'Show', @problem %> |
<%= link_to 'Back', problems_path %>

app/views/problems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Problems</h1>

<div>
  <h3>Filter Problems:</h3>
  <%= form_tag("/problems", method: "get") do %>
    By User: <%= select_tag "user", options_from_collection_for_select(@users, "id", "first_name"), include_blank: true %>

    By Date: <%= select_tag "date", options_for_select(["Today", "Yesterday", "Last week", "Older"]), include_blank: true %>
    <%= submit_tag "Filter" %>
  <% end %>
</div>

<ul>
    <% @problems.each do |problem| %>
      <li><%= link_to problem.title, problem %> - Reported by: <%= link_to problem.user.first_name, user_path(problem.user)%>
          - Reported on: <%= created(problem) %>
        <% if problem.user == current_user %>
      -- <%= link_to 'Edit', edit_problem_path(problem) %>
      <%= link_to 'Destroy', problem, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
    <% end %></li>
</ul>

app/views/problems/new.html.erb
<h1>New Problem</h1>

<%= render 'form', problem: @problem %>

<%= link_to 'Back', problems_path %>

app/views/problems/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @problem.title %>
</p>
<strong>Reported on: </strong>
<p>
<strong>Categories </strong>

  <ul>
    <% @problem.categories.each do |cat| %>
      <li><%= cat.name %></li>
    <% end%>
  </ul>
</p>

<p>
  <strong>Content:</strong>
  <%= @problem.content %>
</p>

<p>
  <strong>Reported by:</strong>
  <%= link_to @problem.user.username, user_path(@problem.user.id) %>
</p>


<% if @problem.user == current_user || current_user.admin%>
  <%= link_to 'Edit', edit_problem_path(@problem) %>
  <%= link_to 'Delete', @problem, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<% @status = @problem.status %>
<% if @status == false %>

  <h3>Submited Proposals</h3>
  <ul>
    <% @problem.proposals.each do |proposal|%>
    <li><%= link_to(proposal.title, problem_proposal_path(@problem, proposal)) %> - Results: <%= vote_results(proposal).round(2) %>% - Reported by: <%= link_to proposal.user.username, user_path(proposal.user.id)%></li>
    <% end %>
  </ul>
<% else %>

    <% voted = 0 %>

    <% current_user.votes.each do |vote|%>
    <% @problem.proposals.each do |proposal| %>
      <% if vote.proposal == proposal %>
          <% voted += 1%>
        <% end %>
    <% end %>
    <% end %>

    <% if voted == 0 %>
      <% @voted_status = false%>
    <% else %>
      <% @voted_status = true%>
    <% end %>


    <% if @voted_status == true || @problem.declare_winner == true %>
    You have already voted<br><br>
    Proposals Vote Results<br>

    <ul>
      <% @problem.proposals.each do |proposal|%>
      <li><%= link_to(proposal.title, problem_proposal_path(@problem, proposal)) %> - Received <%= vote_count(proposal) %> votes - Results: <%= vote_results(proposal).round(2) %>%</li>
      <% end %>
    </ul>

    The winning proposal is <%= winner.title %>


    <% else %>
    Please Vote for the best Proposal
      <%= render 'vote_form', problem: @problem %>

    <% end %>
<% end %><br><br>

<h4>Comments </h4>
  <% @problem.comments.each do |comment|%>
    <p>
      <%= comment.user.email %> says: <br>
      <%= comment.content%><br>
    </p>
  <% end %>

<h4> Users that have commented on this problem:</h4>
  <% @problem.users.to_set.each do |user|%>
    <li><%= user.email%> </li>
  <% end %>

  <h4> Add Comment</h4>

  <%= form_for Comment.new do |f| %>

    <%= f.hidden_field :problem_id, value: @problem.id%>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.label :content %>
    <%= f.text_area :content %>


      <br></br>
    <%= f.submit %>
  <% end %>

<% if @status == false %>
<%= link_to 'Submit A Proposal', new_problem_proposal_path(@problem) %>
<% end %>

<%= link_to 'Back', problems_path %>