config/routes.rb
Rails.application.routes.draw do

  resources :problems do
    resources :proposals do
      resources :materials
    end
  end
  resources :proposals, only:[:index, :show, :edit, :update, :destroy]
  resources :materials, only:[:index, :show, :edit, :update, :destroy]
  resources :categories
  resources :comments
  resources :proposal_comments
  #resources :votes, only:[:create]


  post '/problems/:id', to: "problems#create_vote", as: "create_vote"
  #post '/problems/:id', to: "votes#create"

  root to: 'pages#home'
  #devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'users/:id', to: 'users#show', as: "user"
end

app/views/pages/home.html.erb
<% if user_signed_in?%>
  <h2>Dashboard for: <%= current_user ? current_user.first_name : nil  %></h2>


  <h3>Reported Problems</h3>

  <ul>

    <% @problems.each do |problem| %>
      <li><%=link_to problem.title, problem %> </li>
    <% end %>
  </ul>

  <h3>Submited Proposals:</h3>
  <ul>

    <%@proposals.each do |proposal| %>
      <li><%= link_to proposal.title, problem_proposal_path(proposal.problem, proposal) %> for problem <%= link_to proposal.problem.title, problem_path(proposal.problem) %> -- Reported by - <%= link_to proposal.problem.user.username, user_path(proposal.user.id)%> </li>
    <% end %>
  </ul>




<% else %>
  <h3>Please sign in or Sign up!</h3>
<% end %>