config/routes.rb
Rails.application.routes.draw do

  resources :problems do
    resources :proposals do
      resources :materials
    end
  end
  resources :proposals, only:[:index, :show, :edit, :update, :destroy]
  resources :materials, only:[:index, :show, :edit, :update, :destroy]
  resources :categories
  resources :comments
  resources :proposal_comments
  #resources :votes, only:[:create]


  post '/problems/:id', to: "problems#create_vote", as: "create_vote"
  #post '/problems/:id', to: "votes#create"

  root to: 'pages#home'
  #devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'users/:id', to: 'users#show', as: "user"
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  validates :title, uniqueness: true
  validates :title, :content, presence: true
  belongs_to :user
  belongs_to :problem
  has_many :materials, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :proposal_comments, dependent: :destroy
  has_many :users, through: :proposal_comments
  accepts_nested_attributes_for :materials, reject_if: proc { |attributes| attributes['quantity'].blank? || attributes['name'].blank?}

  #default_scope { order(created_at: :desc) }
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :set_proposal, only: [:show, :edit, :update, :destroy]


  def index
    @proposals = Proposal.all
  end


  def show
    set_proposal

    if params[:problem_id]
      set_problem

    end
  end


  def new

    if params[:problem_id]
      set_problem
      @proposal = @problem.proposals.build
      5.times {@proposal.materials.build}
    else
      @proposal = Proposal.new
      5.times {@proposal.materials.build}
    end
  end


  def edit
    if params[:problem_id]
      set_problem
      set_proposal
    else
      set_proposal
    end
  end


  def create
    if params[:problem_id]
      set_problem
      @proposal = @problem.proposals.build(proposal_params)
      @proposal.user = current_user
    else
      @proposal = Proposal.new(proposal_params)
    end ##

      if @proposal.save
        redirect_to problem_proposal_path(@proposal.problem, @proposal), notice: 'Proposal was successfully created.'
      else
        render :new
      end
  end


  def update
    if params[:problem_id]
      set_problem
      set_proposal
        if @proposal.update(proposal_params)
        redirect_to @proposal, notice: 'Proposal was successfully updated.'
        else
          render :edit
        end
    else

      if @proposal.update(proposal_params)
        redirect_to @proposal, notice: 'Proposal was successfully updated.'
      else
        render :edit
      end
  end
  end


  def destroy
    if params[:problem_id]
  set_problem
  set_proposal
  @proposal.destroy
    redirect_to problem_path
  else
    @proposal.destroy
      redirect_to proposals_url, notice: 'Proposal was successfully destroyed.'
      end
  end

  private
    def set_proposal
      @proposal = Proposal.find(params[:id])
    end

    def proposal_params
      params.require(:proposal).permit(:title, :content, materials_attributes:[:id, :name, :quantity])
    end

    def set_problem
      @problem = Problem.find_by_id(params[:problem_id])
    end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
  def created(proposal)
  proposal.created_at.strftime("%m-%d-%y %H:%M")
end
end

app/views/proposals/_form.html.erb
<%= form_with model:[@problem, @proposal], local: :true do |form| %>
<% if @proposal.errors.any? %>
<h5 style="color: red;"><%= @proposal.errors.full_messages.to_sentence %></h5>
<% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <h4>Materials Required</h4>
  <%= form.fields_for :materials do |m| %>

  <div class="field">
    <%= m.label :name %>
    <%= m.text_field :name%>
  </div>

  <div class="field">
    <%= m.label :quantity %>
    <%= m.number_field :quantity%><br>
  </div>

<% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/proposals/edit.html.erb
<h1>Editing Proposal</h1>

<%= render 'form', proposal: @proposal %>

<%= link_to 'Show', @proposal %> |
<%= link_to 'Back', proposals_path %>

app/views/proposals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proposals</h1>

<ul>
    <% @proposals.each do |proposal| %>
    <li>  <%= link_to proposal.title, proposal_path(proposal) %> for problem <%= link_to proposal.problem.title, problem_path(proposal.problem) %> -- Reported by: <%= proposal.user.username%>

      <% if proposal.user == current_user %>
      <%= link_to 'Edit', edit_proposal_path(proposal) %>
      <%= link_to 'Destroy', proposal, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      <% end %>
    <% end %>
  <ul>

<br>

app/views/proposals/new.html.erb
<h1>New Proposal</h1>

<%= render 'form', proposal: @proposal %>

<%= link_to 'Back', proposals_path %>

app/views/proposals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @proposal.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @proposal.content %>
</p>

<p>
  <strong>Proposed by:</strong>
  <%= @proposal.user.username %>
</p>

<% w=winner %>
<% flg=false %>
<% if w!= nil && w.id == @proposal.id%>
<% flg=true %>
<% end %>
<h4>win status: <%= flg %> </h4>

<p>
  <% if @problem%>
    <strong>Problem:</strong>
    <%= link_to @proposal.problem.title, problem_path(@problem) %>
  <% else%>
    <strong>Problem:</strong>
    <%= link_to @proposal.problem.title, problem_path(@proposal.problem) %>
  <% end %>
</p>
<h4>Materials Required:<h4>
  <ul>
    <% @proposal.materials.each do |material| %>
    <li><%= material.quantity%> - <%=  link_to material.name, problem_proposal_material_path(material.proposal.problem, material.proposal, material)  %> </li>
    <% end %>
  </ul>

  <h4>Comments </h4>
    <% @proposal.proposal_comments.each do |comment|%>
      <p>
        <%= comment.user.email %> says: <br>
        <%= comment.content%><br>
      </p>
    <% end %>

    <h4> Users that have commented on this proposal:</h4>
      <% @proposal.users.to_set.each do |user|%>
        <li><%= user.email%> </li>
      <% end %>

    <h4> Add Comment</h4>

    <%= form_for ProposalComment.new do |f| %>
      <%= f.hidden_field :proposal_id, value: @proposal.id%>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.label :content %>
      <%= f.text_area :content %>


        <br></br>
      <%= f.submit %>
    <% end %>

<% if @proposal.user == current_user || current_user.admin%>
<%= link_to 'Edit', edit_proposal_path(@proposal) %> |
<%= link_to 'Delete', @proposal, method: :delete, data: { confirm: 'Are you sure?' } %>

<% end %>
<h6><%= link_to("Return to Problem", problem_path(@proposal.problem)) %></h6>
<% if @problem%>
  <%= link_to 'Back', problem_path(@problem) %>
<% else %>
  <%= link_to 'Back', root_path %>
<% end %>