config/routes.rb
Rails.application.routes.draw do

  resources :problems do
    resources :proposals do
      resources :materials
    end
  end
  resources :proposals, only:[:index, :show, :edit, :update, :destroy]
  resources :materials, only:[:index, :show, :edit, :update, :destroy]
  resources :categories
  resources :comments
  resources :proposal_comments
  #resources :votes, only:[:create]


  post '/problems/:id', to: "problems#create_vote", as: "create_vote"
  #post '/problems/:id', to: "votes#create"

  root to: 'pages#home'
  #devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'users/:id', to: 'users#show', as: "user"
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :proposal
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]


  def index
    if params[:proposal_id]
        set_proposal
        set_problem
        @materials = @proposal.materials
      else
        @materials = Material.all
      end
  end


  def show
    set_material
    if params[:proposal_id]
      set_proposal
      set_problem
    end
  end

  def new
    if params[:proposal_id]
      set_proposal
      @material = @proposal.materials.build
    else
      @material = Material.new
    end

  end

  def edit
    if params[:problem_id]
      set_problem
      set_proposal
      set_material
    else
      set_proposal
    end
  end


  def create
    if params[:proposal_id]
      set_proposal
      @material = @proposal.materials.build(materical_params)
  else
      @material = Material.new(material_params)
  end
      if @material.save
        redirect_to @material, notice: 'Material was successfully created.'
      else
        render :new
      end
  end


  def update
      if @material.update(material_params)
      redirect_to @material, notice: 'Material was successfully updated.'
      else
        render :edit
      end
  end


  def destroy
    @material.destroy
      redirect_to materials_url, notice: 'Material was successfully destroyed.'
  end

  private
    def set_material
      @material = Material.find(params[:id])
    end

    def material_params
      params.require(:material).permit(:name, :quantity)
    end

    def set_proposal
      @proposal = Proposal.find_by_id(params[:proposal_id])
    end

    def set_problem
      @problem = Problem.find_by_id(params[:problem_id])
    end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/_form.html.erb
<%= form_with(model: material, local: true) do |form| %>
  <% if material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
        <% material.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/materials/edit.html.erb
<h1>Editing Material</h1>

<%= render 'form', material: @material %>

<%= link_to 'Show', @material %> |
<%= link_to 'Back', materials_path %>

app/views/materials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Materials</h1>

<ul>
    <% @materials.each do |material| %>
      <li>  <%= link_to material.name, material %></li>
    <% end %>
</ul>

<br>

app/views/materials/new.html.erb
<h1>New Material</h1>

<%= render 'form', material: @material %>

<%= link_to 'Back', materials_path %>

app/views/materials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @material.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @material.quantity %>
</p>

<p>
  <strong>Proposal:</strong>
  <%= @material.proposal_id %>
</p>
<% if @material.proposal.user == current_user || current_user.admin%>
<%= link_to 'Edit', edit_problem_proposal_material_path(@material.proposal.problem, @material.proposal, @material) %> |
<% end %>
<%= link_to 'Back', materials_path %>